[profile.default]
src = 'contracts'
out = 'forge-artifacts'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'

optimizer = true
optimizer_runs = 9999
ignored_error_codes = [8261]

[fuzz]
runs = 10000
max_test_rejects = 60000

[profile.intense.fuzz]
verbosity = 3
runs = 100000
max_test_rejects = 600000
